# Site metadata.

# Canonical URL
url: https://nrkbeta.no/https-norge

name: "HTTPS-status Norge"
title: "HTTPS-status Norge"
description: "Hvor stor andel av domener eid av det offentlige i Norge bruker HTTPS?"

# When the data we used was generated. Manually updated for now.
data:
  # URL where we download the .gov domain list from.
  domains_url: https://byeskille.no/norway-gov-domains/data/domains.csv
  analytics_url: ''
