# Site metadata.

# Canonical URL
url: https://nrkbeta.no/https-norge

name: "HTTPS-status Norge"
title: "HTTPS-status Norge"
description: "Hvor stor andel av domener eid av det offentlige i Norge bruker HTTPS?"

# Data sources. These URLs should have their content updated in-place.
data:
  # URL where we download the .gov domain list from.
  domains_url: "https://raw.githubusercontent.com/byeskille/norway-gov-domains/master/data/domains.csv"

  # URL where we download the participating DAP .gov list from.
  analytics_url: ""

  # DAP URL where we source public .gov subdomains from.
  analytics_subdomains_url: ""

bucket: unused
