# Site metadata.

# Canonical URL
url: https://nrkbeta.no/https-norge

name: "HTTPS-status Kommune-Norge"
title: "HTTPS-status Kommune-Norge"
description: "Hvor stor andel av offisielle .kommune.no-domener bruker HTTPS?"

# Data sources. These URLs should have their content updated in-place.
data:
  # URL where we download the .gov domain list from.
  domains_url: "https://byeskille.no/norway-gov-domains/data/domains.local.kommune.csv"

  # URL where we download the participating DAP .gov list from.
  analytics_url: ""

  # DAP URL where we source public .gov subdomains from.
  analytics_subdomains_url: ""

bucket: unused
