# Site metadata.

# Canonical URL
url: https://https.jetzt

name: "https.jetzt!"
title: "https.jetzt!"
description: "Zu wie vielen Behördenwebsites ist eine sichere, verschlüsselte Verbindung möglich?"

# Data source URLs. They shouldn't require manual updates.
data:
  # URL where we download the .gov domain list from.
  domains_url: https://raw.githubusercontent.com/robbi5/german-gov-domains/master/data/domains.csv
  analytics_url: ''
